import Head from "next/head"
import { useRouter } from "next/router";
import { useState } from "react"

export default function Header(){
    const router = useRouter();

  // Mapa tytułów stron w zależności od ścieżki
  const pageTitles = {
    "/": "Logo",
    "/create-sheet": "Stwórz arkusz",
    "/select-sheet": "Wybierz arkusz",
    "/browse-reports": "Przeglądaj raporty",
  };

  // Pobranie tytułu na podstawie obecnej ścieżki
    const currentPath = router.pathname;
    const title = pageTitles[currentPath] || "Podstrona";
    
    return(
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}


